export const FETCH_FLIGHTS = "FETCH_FLIGHTS";
export const SEARCH_FLIGHTS = "SEARCH_FLIGHTS";
export const SEARCH_RETURN_FLIGHTS = "SEARCH_RETURN_FLIGHTS";
export const SELECT_RETURN_FLIGHT = "SELECT_RETURN_FLIGHT";
export const SELECT_FLIGHT = "SELECT_FLIGHT";
export const SELECT_SEAT = "SELECT_SEAT";
export const REMOVE_SEAT = "REMOVE_SEAT";
export const CREATE_TICKET = "CREATE_TICKET";
export const FETCH_AIRPORTS = "FETCH_AIRPORTS";
export const REMOVE_RETURN_SEAT = "REMOVE_RETURN_SEAT";
export const SELECT_RETURN_SEAT = "SELECT_RETURN_SEAT";

export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST";
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS";
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL";
